// Zomawia Sailo
// zomawia@gmail.com

//Problem: Fibonacci Sequence
//
//	The fibonacci sequence is a series of numbers used in evaluating the golden ratio or the numerical constant phi.
//  Numbers in the sequence are generated by adding the two numbers that precede it in the sequence, starting with 0 and 1.
//
//	Input :
//	K : The number of fibonacci numbers to output.
//
//	Where K is a positive integer.
//
//	Output :
//	The first K fibonacci numbers.
//
//	Example Input :
//		 10
//
//			 Example Output :
//		 0, 1, 1, 2, 3, 5, 8, 13, 21, 34


#include <iostream>

int main()
{
	int input;

	int CurA = 0,
		CurB = 1,
		Sum = 0;
		

	printf("Fibonacci Sequence. Enter in a number: \n>>");
	scanf_s("%d", &input);

	printf("\nFibonacci time\n\n:");

	printf("%d %d ", CurA, CurB);

	for (int i = input; i > 2; i--)
	{
		Sum = CurA + CurB;
		CurA = CurB;
		CurB = Sum;
		printf("%d ", CurB);
	}

	system("pause");

}